places = ['japan', 'mexico', 'britain', 'tibet', 'canada']
print('Original list:')
print(places)
print('Sorted list:')
print(sorted(places))
print('Original list again:')
print(places)
places.reverse()
print('Now backwards:')
print(places)
places.reverse()
print('Original order again:')
print(places)
places.sort()
print('Sorted:')
print(places)
places.sort(reverse=True)
print('Sorted in reverse order:')
print(places)
